name: Bug Report
description: When something is not working as expected
labels: [bug]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: input
  attributes:
    label: SkyAura Version Number
    placeholder: 1234.56.78.890 (USE AN ACTUAL VERSION NUMBER)
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: |
      Add media to help explain your problem
  validations:
    required: false
- type: textarea
  attributes:
    label: Log Files
    description: |
      Add media to help explain your problem
  validations:
    required: true
