name: Bug Report
description: When something is not working as expected
labels: [bug]
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: false
- type: textarea
  attributes:
    label: To reproduce
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: SkyAura Version Number
    description: |
    placeholder: 2024.12.15.0621 (USE AN ACTUAL VERSION NUMBER)
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
